# Generated by Django 4.2.29 on 2026-03-28 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0068_issue_cached_display_title_a11y_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='cached_display_title_a11y_cy',
            new_name='cached_display_title_a11y_kk',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='cached_display_title_a11y_de',
            new_name='cached_display_title_a11y_ru',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='cached_display_title_cy',
            new_name='cached_display_title_kk',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='cached_display_title_de',
            new_name='cached_display_title_ru',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='contact_info_cy',
            new_name='contact_info_kk',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='contact_info_de',
            new_name='contact_info_ru',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='cached_display_title_a11y_en_us',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='cached_display_title_a11y_es',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='cached_display_title_a11y_fr',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='cached_display_title_a11y_nl',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='cached_display_title_en_us',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='cached_display_title_es',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='cached_display_title_fr',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='cached_display_title_nl',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='contact_info_en_us',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='contact_info_es',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='contact_info_fr',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='contact_info_nl',
        ),
    ]
